#kernel:
  #name: mykernel
  #spec: kernels/mykernel/kernel.json

  # JupyterLite Configuration File

# Add any additional configurations here

# Pip Packages
lite_extra_requirements:
  - biosimulators-copasi

# Include the custom JupyterLite extension
lite_include_extensions:
  - jupyterlite_boilerplate

# JupyterLite Deployment Settings
lite:
  version: 0.2.0
  remote_storage: true
  basepath: "/biosimulators-sandbox-test-repo-2"
  kernel:
    start_timeout: 60